/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void   request__socket__init
                     (Request__Socket         *message)
{
  static Request__Socket init_value = REQUEST__SOCKET__INIT;
  *message = init_value;
}
void   request__connect__init
                     (Request__Connect         *message)
{
  static Request__Connect init_value = REQUEST__CONNECT__INIT;
  *message = init_value;
}
void   request__close__init
                     (Request__Close         *message)
{
  static Request__Close init_value = REQUEST__CLOSE__INIT;
  *message = init_value;
}
void   request__recvfrom__init
                     (Request__Recvfrom         *message)
{
  static Request__Recvfrom init_value = REQUEST__RECVFROM__INIT;
  *message = init_value;
}
void   request__sendto__init
                     (Request__Sendto         *message)
{
  static Request__Sendto init_value = REQUEST__SENDTO__INIT;
  *message = init_value;
}
void   request__poll__init
                     (Request__Poll         *message)
{
  static Request__Poll init_value = REQUEST__POLL__INIT;
  *message = init_value;
}
void   request__select__init
                     (Request__Select         *message)
{
  static Request__Select init_value = REQUEST__SELECT__INIT;
  *message = init_value;
}
void   request__getpeername__init
                     (Request__Getpeername         *message)
{
  static Request__Getpeername init_value = REQUEST__GETPEERNAME__INIT;
  *message = init_value;
}
void   request__getsockname__init
                     (Request__Getsockname         *message)
{
  static Request__Getsockname init_value = REQUEST__GETSOCKNAME__INIT;
  *message = init_value;
}
void   request__getsockopt__init
                     (Request__Getsockopt         *message)
{
  static Request__Getsockopt init_value = REQUEST__GETSOCKOPT__INIT;
  *message = init_value;
}
void   request__setsockopt__init
                     (Request__Setsockopt         *message)
{
  static Request__Setsockopt init_value = REQUEST__SETSOCKOPT__INIT;
  *message = init_value;
}
void   request__fcntl__init
                     (Request__Fcntl         *message)
{
  static Request__Fcntl init_value = REQUEST__FCNTL__INIT;
  *message = init_value;
}
void   request__atstart__init
                     (Request__Atstart         *message)
{
  static Request__Atstart init_value = REQUEST__ATSTART__INIT;
  *message = init_value;
}
void   request__init
                     (Request         *message)
{
  static Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request__socket__field_descriptors[3] =
{
  {
    "domain",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request__Socket, domain),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request__Socket, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protocol",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request__Socket, protocol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__socket__field_indices_by_name[] = {
  0,   /* field[0] = domain */
  2,   /* field[2] = protocol */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange request__socket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor request__socket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Socket",
  "Socket",
  "Request__Socket",
  "",
  sizeof(Request__Socket),
  3,
  request__socket__field_descriptors,
  request__socket__field_indices_by_name,
  1,  request__socket__number_ranges,
  (ProtobufCMessageInit) request__socket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__connect__field_descriptors[1] =
{
  {
    "addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Request__Connect, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__connect__field_indices_by_name[] = {
  0,   /* field[0] = addr */
};
static const ProtobufCIntRange request__connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Connect",
  "Connect",
  "Request__Connect",
  "",
  sizeof(Request__Connect),
  1,
  request__connect__field_descriptors,
  request__connect__field_indices_by_name,
  1,  request__connect__number_ranges,
  (ProtobufCMessageInit) request__connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__close__field_descriptors NULL
#define request__close__field_indices_by_name NULL
#define request__close__number_ranges NULL
const ProtobufCMessageDescriptor request__close__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Close",
  "Close",
  "Request__Close",
  "",
  sizeof(Request__Close),
  0,
  request__close__field_descriptors,
  request__close__field_indices_by_name,
  0,  request__close__number_ranges,
  (ProtobufCMessageInit) request__close__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__recvfrom__field_descriptors[3] =
{
  {
    "len",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request__Recvfrom, len),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request__Recvfrom, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requireAddr",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Request__Recvfrom, requireaddr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__recvfrom__field_indices_by_name[] = {
  1,   /* field[1] = flags */
  0,   /* field[0] = len */
  2,   /* field[2] = requireAddr */
};
static const ProtobufCIntRange request__recvfrom__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor request__recvfrom__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Recvfrom",
  "Recvfrom",
  "Request__Recvfrom",
  "",
  sizeof(Request__Recvfrom),
  3,
  request__recvfrom__field_descriptors,
  request__recvfrom__field_indices_by_name,
  1,  request__recvfrom__number_ranges,
  (ProtobufCMessageInit) request__recvfrom__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__sendto__field_descriptors[3] =
{
  {
    "buf",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Request__Sendto, buf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request__Sendto, flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Request__Sendto, has_addr),
    offsetof(Request__Sendto, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__sendto__field_indices_by_name[] = {
  2,   /* field[2] = addr */
  0,   /* field[0] = buf */
  1,   /* field[1] = flags */
};
static const ProtobufCIntRange request__sendto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor request__sendto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Sendto",
  "Sendto",
  "Request__Sendto",
  "",
  sizeof(Request__Sendto),
  3,
  request__sendto__field_descriptors,
  request__sendto__field_indices_by_name,
  1,  request__sendto__number_ranges,
  (ProtobufCMessageInit) request__sendto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__poll__field_descriptors NULL
#define request__poll__field_indices_by_name NULL
#define request__poll__number_ranges NULL
const ProtobufCMessageDescriptor request__poll__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Poll",
  "Poll",
  "Request__Poll",
  "",
  sizeof(Request__Poll),
  0,
  request__poll__field_descriptors,
  request__poll__field_indices_by_name,
  0,  request__poll__number_ranges,
  (ProtobufCMessageInit) request__poll__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__select__field_descriptors NULL
#define request__select__field_indices_by_name NULL
#define request__select__number_ranges NULL
const ProtobufCMessageDescriptor request__select__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Select",
  "Select",
  "Request__Select",
  "",
  sizeof(Request__Select),
  0,
  request__select__field_descriptors,
  request__select__field_indices_by_name,
  0,  request__select__number_ranges,
  (ProtobufCMessageInit) request__select__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__getpeername__field_descriptors NULL
#define request__getpeername__field_indices_by_name NULL
#define request__getpeername__number_ranges NULL
const ProtobufCMessageDescriptor request__getpeername__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Getpeername",
  "Getpeername",
  "Request__Getpeername",
  "",
  sizeof(Request__Getpeername),
  0,
  request__getpeername__field_descriptors,
  request__getpeername__field_indices_by_name,
  0,  request__getpeername__number_ranges,
  (ProtobufCMessageInit) request__getpeername__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__getsockname__field_descriptors NULL
#define request__getsockname__field_indices_by_name NULL
#define request__getsockname__number_ranges NULL
const ProtobufCMessageDescriptor request__getsockname__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Getsockname",
  "Getsockname",
  "Request__Getsockname",
  "",
  sizeof(Request__Getsockname),
  0,
  request__getsockname__field_descriptors,
  request__getsockname__field_indices_by_name,
  0,  request__getsockname__number_ranges,
  (ProtobufCMessageInit) request__getsockname__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__getsockopt__field_descriptors NULL
#define request__getsockopt__field_indices_by_name NULL
#define request__getsockopt__number_ranges NULL
const ProtobufCMessageDescriptor request__getsockopt__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Getsockopt",
  "Getsockopt",
  "Request__Getsockopt",
  "",
  sizeof(Request__Getsockopt),
  0,
  request__getsockopt__field_descriptors,
  request__getsockopt__field_indices_by_name,
  0,  request__getsockopt__number_ranges,
  (ProtobufCMessageInit) request__getsockopt__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__setsockopt__field_descriptors NULL
#define request__setsockopt__field_indices_by_name NULL
#define request__setsockopt__number_ranges NULL
const ProtobufCMessageDescriptor request__setsockopt__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Setsockopt",
  "Setsockopt",
  "Request__Setsockopt",
  "",
  sizeof(Request__Setsockopt),
  0,
  request__setsockopt__field_descriptors,
  request__setsockopt__field_indices_by_name,
  0,  request__setsockopt__number_ranges,
  (ProtobufCMessageInit) request__setsockopt__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define request__fcntl__field_descriptors NULL
#define request__fcntl__field_indices_by_name NULL
#define request__fcntl__number_ranges NULL
const ProtobufCMessageDescriptor request__fcntl__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Fcntl",
  "Fcntl",
  "Request__Fcntl",
  "",
  sizeof(Request__Fcntl),
  0,
  request__fcntl__field_descriptors,
  request__fcntl__field_indices_by_name,
  0,  request__fcntl__number_ranges,
  (ProtobufCMessageInit) request__fcntl__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__atstart__field_descriptors[1] =
{
  {
    "progname",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Request__Atstart, progname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__atstart__field_indices_by_name[] = {
  0,   /* field[0] = progname */
};
static const ProtobufCIntRange request__atstart__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__atstart__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.Atstart",
  "Atstart",
  "Request__Atstart",
  "",
  sizeof(Request__Atstart),
  1,
  request__atstart__field_descriptors,
  request__atstart__field_indices_by_name,
  1,  request__atstart__number_ranges,
  (ProtobufCMessageInit) request__atstart__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[14] =
{
  {
    "socketCall",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, socketcall),
    &request__socket__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectCall",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, connectcall),
    &request__connect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeCall",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, closecall),
    &request__close__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recvfromCall",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, recvfromcall),
    &request__recvfrom__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sendtoCall",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, sendtocall),
    &request__sendto__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pollCall",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, pollcall),
    &request__poll__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "selectCall",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, selectcall),
    &request__select__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getpeernameCall",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, getpeernamecall),
    &request__getpeername__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getsocknameCall",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, getsocknamecall),
    &request__getsockname__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getsockoptCall",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, getsockoptcall),
    &request__getsockopt__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setsockoptCall",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, setsockoptcall),
    &request__setsockopt__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fcntlCall",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, fcntlcall),
    &request__fcntl__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Request, pid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atstartAction",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Request, calling_case),
    offsetof(Request, atstartaction),
    &request__atstart__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  13,   /* field[13] = atstartAction */
  2,   /* field[2] = closeCall */
  1,   /* field[1] = connectCall */
  11,   /* field[11] = fcntlCall */
  7,   /* field[7] = getpeernameCall */
  8,   /* field[8] = getsocknameCall */
  9,   /* field[9] = getsockoptCall */
  12,   /* field[12] = pid */
  5,   /* field[5] = pollCall */
  3,   /* field[3] = recvfromCall */
  6,   /* field[6] = selectCall */
  4,   /* field[4] = sendtoCall */
  10,   /* field[10] = setsockoptCall */
  0,   /* field[0] = socketCall */
};
static const ProtobufCIntRange request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 15, 12 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  14,
  request__field_descriptors,
  request__field_indices_by_name,
  2,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
