/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "response.pb-c.h"
void   response__socket__init
                     (Response__Socket         *message)
{
  static Response__Socket init_value = RESPONSE__SOCKET__INIT;
  *message = init_value;
}
void   response__connect__init
                     (Response__Connect         *message)
{
  static Response__Connect init_value = RESPONSE__CONNECT__INIT;
  *message = init_value;
}
void   response__close__init
                     (Response__Close         *message)
{
  static Response__Close init_value = RESPONSE__CLOSE__INIT;
  *message = init_value;
}
void   response__recvfrom__init
                     (Response__Recvfrom         *message)
{
  static Response__Recvfrom init_value = RESPONSE__RECVFROM__INIT;
  *message = init_value;
}
void   response__sendto__init
                     (Response__Sendto         *message)
{
  static Response__Sendto init_value = RESPONSE__SENDTO__INIT;
  *message = init_value;
}
void   response__poll__init
                     (Response__Poll         *message)
{
  static Response__Poll init_value = RESPONSE__POLL__INIT;
  *message = init_value;
}
void   response__select__init
                     (Response__Select         *message)
{
  static Response__Select init_value = RESPONSE__SELECT__INIT;
  *message = init_value;
}
void   response__getpeername__init
                     (Response__Getpeername         *message)
{
  static Response__Getpeername init_value = RESPONSE__GETPEERNAME__INIT;
  *message = init_value;
}
void   response__getsockname__init
                     (Response__Getsockname         *message)
{
  static Response__Getsockname init_value = RESPONSE__GETSOCKNAME__INIT;
  *message = init_value;
}
void   response__getsockopt__init
                     (Response__Getsockopt         *message)
{
  static Response__Getsockopt init_value = RESPONSE__GETSOCKOPT__INIT;
  *message = init_value;
}
void   response__setsockopt__init
                     (Response__Setsockopt         *message)
{
  static Response__Setsockopt init_value = RESPONSE__SETSOCKOPT__INIT;
  *message = init_value;
}
void   response__fcntl__init
                     (Response__Fcntl         *message)
{
  static Response__Fcntl init_value = RESPONSE__FCNTL__INIT;
  *message = init_value;
}
void   response__atstart__init
                     (Response__Atstart         *message)
{
  static Response__Atstart init_value = RESPONSE__ATSTART__INIT;
  *message = init_value;
}
void   response__atfork__init
                     (Response__Atfork         *message)
{
  static Response__Atfork init_value = RESPONSE__ATFORK__INIT;
  *message = init_value;
}
void   response__atexit__init
                     (Response__Atexit         *message)
{
  static Response__Atexit init_value = RESPONSE__ATEXIT__INIT;
  *message = init_value;
}
void   response__init
                     (Response         *message)
{
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor response__socket__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Socket, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Socket, has_errno_),
    offsetof(Response__Socket, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__socket__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__socket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__socket__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Socket",
  "Socket",
  "Response__Socket",
  "",
  sizeof(Response__Socket),
  2,
  response__socket__field_descriptors,
  response__socket__field_indices_by_name,
  1,  response__socket__number_ranges,
  (ProtobufCMessageInit) response__socket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__connect__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Connect, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Connect, has_errno_),
    offsetof(Response__Connect, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__connect__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__connect__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__connect__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Connect",
  "Connect",
  "Response__Connect",
  "",
  sizeof(Response__Connect),
  2,
  response__connect__field_descriptors,
  response__connect__field_indices_by_name,
  1,  response__connect__number_ranges,
  (ProtobufCMessageInit) response__connect__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__close__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Close, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Close, has_errno_),
    offsetof(Response__Close, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__close__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__close__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__close__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Close",
  "Close",
  "Response__Close",
  "",
  sizeof(Response__Close),
  2,
  response__close__field_descriptors,
  response__close__field_indices_by_name,
  1,  response__close__number_ranges,
  (ProtobufCMessageInit) response__close__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__recvfrom__field_descriptors[4] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Recvfrom, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Recvfrom, has_errno_),
    offsetof(Response__Recvfrom, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buf",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__Recvfrom, has_buf),
    offsetof(Response__Recvfrom, buf),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "addr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__Recvfrom, has_addr),
    offsetof(Response__Recvfrom, addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__recvfrom__field_indices_by_name[] = {
  3,   /* field[3] = addr */
  2,   /* field[2] = buf */
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__recvfrom__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor response__recvfrom__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Recvfrom",
  "Recvfrom",
  "Response__Recvfrom",
  "",
  sizeof(Response__Recvfrom),
  4,
  response__recvfrom__field_descriptors,
  response__recvfrom__field_indices_by_name,
  1,  response__recvfrom__number_ranges,
  (ProtobufCMessageInit) response__recvfrom__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__sendto__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Sendto, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Sendto, has_errno_),
    offsetof(Response__Sendto, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__sendto__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__sendto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__sendto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Sendto",
  "Sendto",
  "Response__Sendto",
  "",
  sizeof(Response__Sendto),
  2,
  response__sendto__field_descriptors,
  response__sendto__field_indices_by_name,
  1,  response__sendto__number_ranges,
  (ProtobufCMessageInit) response__sendto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__poll__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Poll, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Poll, has_errno_),
    offsetof(Response__Poll, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__poll__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__poll__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__poll__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Poll",
  "Poll",
  "Response__Poll",
  "",
  sizeof(Response__Poll),
  2,
  response__poll__field_descriptors,
  response__poll__field_indices_by_name,
  1,  response__poll__number_ranges,
  (ProtobufCMessageInit) response__poll__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__select__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Select, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Select, has_errno_),
    offsetof(Response__Select, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__select__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__select__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__select__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Select",
  "Select",
  "Response__Select",
  "",
  sizeof(Response__Select),
  2,
  response__select__field_descriptors,
  response__select__field_indices_by_name,
  1,  response__select__number_ranges,
  (ProtobufCMessageInit) response__select__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__getpeername__field_descriptors[3] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Getpeername, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Getpeername, has_errno_),
    offsetof(Response__Getpeername, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peername",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__Getpeername, has_peername),
    offsetof(Response__Getpeername, peername),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__getpeername__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  2,   /* field[2] = peername */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__getpeername__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor response__getpeername__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Getpeername",
  "Getpeername",
  "Response__Getpeername",
  "",
  sizeof(Response__Getpeername),
  3,
  response__getpeername__field_descriptors,
  response__getpeername__field_indices_by_name,
  1,  response__getpeername__number_ranges,
  (ProtobufCMessageInit) response__getpeername__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__getsockname__field_descriptors[3] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Getsockname, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Getsockname, has_errno_),
    offsetof(Response__Getsockname, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sockanme",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__Getsockname, has_sockanme),
    offsetof(Response__Getsockname, sockanme),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__getsockname__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
  2,   /* field[2] = sockanme */
};
static const ProtobufCIntRange response__getsockname__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor response__getsockname__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Getsockname",
  "Getsockname",
  "Response__Getsockname",
  "",
  sizeof(Response__Getsockname),
  3,
  response__getsockname__field_descriptors,
  response__getsockname__field_indices_by_name,
  1,  response__getsockname__number_ranges,
  (ProtobufCMessageInit) response__getsockname__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__getsockopt__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Getsockopt, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Getsockopt, has_errno_),
    offsetof(Response__Getsockopt, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__getsockopt__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__getsockopt__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__getsockopt__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Getsockopt",
  "Getsockopt",
  "Response__Getsockopt",
  "",
  sizeof(Response__Getsockopt),
  2,
  response__getsockopt__field_descriptors,
  response__getsockopt__field_indices_by_name,
  1,  response__getsockopt__number_ranges,
  (ProtobufCMessageInit) response__getsockopt__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__setsockopt__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Setsockopt, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Setsockopt, has_errno_),
    offsetof(Response__Setsockopt, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__setsockopt__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__setsockopt__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__setsockopt__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Setsockopt",
  "Setsockopt",
  "Response__Setsockopt",
  "",
  sizeof(Response__Setsockopt),
  2,
  response__setsockopt__field_descriptors,
  response__setsockopt__field_indices_by_name,
  1,  response__setsockopt__number_ranges,
  (ProtobufCMessageInit) response__setsockopt__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__fcntl__field_descriptors[2] =
{
  {
    "ret",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Fcntl, ret),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errno_",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Fcntl, has_errno_),
    offsetof(Response__Fcntl, errno_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__fcntl__field_indices_by_name[] = {
  1,   /* field[1] = errno_ */
  0,   /* field[0] = ret */
};
static const ProtobufCIntRange response__fcntl__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__fcntl__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Fcntl",
  "Fcntl",
  "Response__Fcntl",
  "",
  sizeof(Response__Fcntl),
  2,
  response__fcntl__field_descriptors,
  response__fcntl__field_indices_by_name,
  1,  response__fcntl__number_ranges,
  (ProtobufCMessageInit) response__fcntl__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__atstart__field_descriptors[2] =
{
  {
    "startfd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Response__Atstart, startfd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Response__Atstart, has_count),
    offsetof(Response__Atstart, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__atstart__field_indices_by_name[] = {
  1,   /* field[1] = count */
  0,   /* field[0] = startfd */
};
static const ProtobufCIntRange response__atstart__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__atstart__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Atstart",
  "Atstart",
  "Response__Atstart",
  "",
  sizeof(Response__Atstart),
  2,
  response__atstart__field_descriptors,
  response__atstart__field_indices_by_name,
  1,  response__atstart__number_ranges,
  (ProtobufCMessageInit) response__atstart__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define response__atfork__field_descriptors NULL
#define response__atfork__field_indices_by_name NULL
#define response__atfork__number_ranges NULL
const ProtobufCMessageDescriptor response__atfork__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Atfork",
  "Atfork",
  "Response__Atfork",
  "",
  sizeof(Response__Atfork),
  0,
  response__atfork__field_descriptors,
  response__atfork__field_indices_by_name,
  0,  response__atfork__number_ranges,
  (ProtobufCMessageInit) response__atfork__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define response__atexit__field_descriptors NULL
#define response__atexit__field_indices_by_name NULL
#define response__atexit__number_ranges NULL
const ProtobufCMessageDescriptor response__atexit__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.Atexit",
  "Atexit",
  "Response__Atexit",
  "",
  sizeof(Response__Atexit),
  0,
  response__atexit__field_descriptors,
  response__atexit__field_indices_by_name,
  0,  response__atexit__number_ranges,
  (ProtobufCMessageInit) response__atexit__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue response__ret_code__enum_values_by_number[3] =
{
  { "OK", "RESPONSE__RET_CODE__OK", 0 },
  { "ERROR", "RESPONSE__RET_CODE__ERROR", 1 },
  { "WAIT_NEXT", "RESPONSE__RET_CODE__WAIT_NEXT", 2 },
};
static const ProtobufCIntRange response__ret_code__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex response__ret_code__enum_values_by_name[3] =
{
  { "ERROR", 1 },
  { "OK", 0 },
  { "WAIT_NEXT", 2 },
};
const ProtobufCEnumDescriptor response__ret_code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.RetCode",
  "RetCode",
  "Response__RetCode",
  "",
  3,
  response__ret_code__enum_values_by_number,
  3,
  response__ret_code__enum_values_by_name,
  1,
  response__ret_code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[16] =
{
  {
    "socketCall",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, socketcall),
    &response__socket__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "connectCall",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, connectcall),
    &response__connect__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "closeCall",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, closecall),
    &response__close__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recvfromCall",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, recvfromcall),
    &response__recvfrom__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sendtoCall",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, sendtocall),
    &response__sendto__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pollCall",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, pollcall),
    &response__poll__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "selectCall",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, selectcall),
    &response__select__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getpeernameCall",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, getpeernamecall),
    &response__getpeername__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getsocknameCall",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, getsocknamecall),
    &response__getsockname__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getsockoptCall",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, getsockoptcall),
    &response__getsockopt__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "setsockoptCall",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, setsockoptcall),
    &response__setsockopt__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fcntlCall",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, fcntlcall),
    &response__fcntl__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "retCode",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, retcode),
    &response__ret_code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atstartAction",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, atstartaction),
    &response__atstart__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atforkAction",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, atforkaction),
    &response__atfork__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atexitAction",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Response, returning_case),
    offsetof(Response, atexitaction),
    &response__atexit__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  15,   /* field[15] = atexitAction */
  14,   /* field[14] = atforkAction */
  13,   /* field[13] = atstartAction */
  2,   /* field[2] = closeCall */
  1,   /* field[1] = connectCall */
  11,   /* field[11] = fcntlCall */
  7,   /* field[7] = getpeernameCall */
  8,   /* field[8] = getsocknameCall */
  9,   /* field[9] = getsockoptCall */
  5,   /* field[5] = pollCall */
  3,   /* field[3] = recvfromCall */
  12,   /* field[12] = retCode */
  6,   /* field[6] = selectCall */
  4,   /* field[4] = sendtoCall */
  10,   /* field[10] = setsockoptCall */
  0,   /* field[0] = socketCall */
};
static const ProtobufCIntRange response__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 15, 12 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  16,
  response__field_descriptors,
  response__field_indices_by_name,
  2,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
